export const ErrorCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  DUPLICATE_RESOURCE: 'DUPLICATE_RESOURCE',
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  EXPIRED_BATCH: 'EXPIRED_BATCH',
  PRESCRIPTION_REQUIRED: 'PRESCRIPTION_REQUIRED',
  INVALID_PAYMENT: 'INVALID_PAYMENT',
  CONCURRENT_MODIFICATION: 'CONCURRENT_MODIFICATION',
  INTERNAL_ERROR: 'INTERNAL_ERROR'
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];

export const httpStatusForErrorCode: Record<ErrorCodeType, number> = {
  VALIDATION_ERROR: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  DUPLICATE_RESOURCE: 409,
  INSUFFICIENT_STOCK: 409,
  EXPIRED_BATCH: 409,
  PRESCRIPTION_REQUIRED: 422,
  INVALID_PAYMENT: 422,
  CONCURRENT_MODIFICATION: 409,
  INTERNAL_ERROR: 500
};
